# Generated by Django 3.1.2 on 2021-11-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211115_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
    ]
