# Generated by Django 3.1.2 on 2022-02-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_variants_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='takhfif',
            new_name='discount_price',
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.IntegerField(default=0, verbose_name='قیمت خرید'),
        ),
    ]
