# Generated by Django 3.1.2 on 2022-06-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20220219_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.IntegerField(choices=[(1, 'مردانه'), (2, 'زنانه'), (3, 'ست')], verbose_name='جنسیت'),
        ),
    ]
