# Generated by Django 3.1.2 on 2023-01-21 08:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220610_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.AddField(
            model_name='discount',
            name='form',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 8, 33, 10, 627030, tzinfo=utc), verbose_name='From'),
        ),
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ManyToManyField(related_name='discount', to='product.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='discount',
            name='to',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 8, 33, 10, 627030, tzinfo=utc), verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(allow_unicode=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=500, verbose_name='اسلاگ'),
        ),
    ]
