# Generated by Django 3.1.2 on 2023-01-21 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20230121_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='form',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='to',
        ),
        migrations.AddField(
            model_name='discount',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='From'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='To'),
            preserve_default=False,
        ),
    ]
