# Generated by Django 3.1.2 on 2023-01-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_discount_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='man',
            field=models.BooleanField(default=False, verbose_name='Man'),
        ),
        migrations.AddField(
            model_name='product',
            name='women',
            field=models.BooleanField(default=False, verbose_name='Women'),
        ),
    ]
