# Generated by Django 3.1.2 on 2023-01-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20230131_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dis_price',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='dis_price',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_status',
            field=models.BooleanField(default=False, verbose_name='تخفیف'),
        ),
        migrations.AddField(
            model_name='variants',
            name='discount_status',
            field=models.BooleanField(default=False, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف'),
        ),
    ]
