# Generated by Django 3.1.2 on 2021-11-09 22:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('cover', models.ImageField(upload_to='katoni_images/articles', verbose_name='کاور')),
                ('text', ckeditor.fields.RichTextField(verbose_name='متن')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='انتشار')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='به روز رسانی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله ها',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('phone', models.CharField(max_length=60, verbose_name='تلفن')),
                ('address', models.CharField(max_length=60, verbose_name='آدرس')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('email', models.CharField(max_length=60, verbose_name='ایمیل')),
                ('telegram', models.CharField(max_length=60, verbose_name='تلگرام')),
                ('instagram', models.CharField(max_length=60, verbose_name='اینستاگرام')),
                ('icon', models.ImageField(blank=True, upload_to='katoni_images/setting', verbose_name='لوگو')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='به روز رسانی')),
            ],
            options={
                'verbose_name': 'مشخصات',
                'verbose_name_plural': 'مشخصات',
            },
        ),
    ]
