# Generated by Django 3.1.2 on 2021-11-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_delete_shopcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='amount',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='total_price',
            field=models.PositiveIntegerField(default=1, verbose_name='قیمت کامل'),
            preserve_default=False,
        ),
    ]
