# Generated by Django 3.1.2 on 2021-11-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_orderproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
    ]
