# Generated by Django 3.1.2 on 2021-11-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_orderproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='discounts',
        ),
    ]
