# Generated by Django 3.1.2 on 2022-02-16 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220214_1139'),
        ('order', '0012_auto_20220214_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_orderitem', to='product.product', verbose_name='محصول'),
        ),
    ]
